name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'
  workflow_dispatch:

jobs:
  test_suite:
    name: Pytest on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        # os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8']
        # python-version: ['3.8', '3.9', '3.10']
    timeout-minutes: 30
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: install
        run: |
          conda create -n test-env python=${{ matrix.python-version }} -c conda-forge --override-channels
          conda activate test-env
          conda install --file requirements.txt --file requirements-dev.txt -c conda-forge --override-channels
          pip install .
      - name: unit tests
        run: |
          conda activate test-env
          pytest tests
